version: '3'
services:
  db:
    image: mariadb
    container_name: pruebadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pruebadb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
